
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f7f8fa', padding: 20 },
  title: {
    color: '#1f2937',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    padding: 12,
    marginVertical: 30,
    borderRadius: 10,
  },
  btn: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    padding: 14,
    marginVertical: 8,
    alignItems: 'center',
    borderRadius: 10,
  },
  btnText: { color: '#1f2937', fontSize: 16, fontWeight: '600' },
  input: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    color: '#111827',
    padding: 10,
    marginVertical: 8,
    borderRadius: 10,
  },
  row: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    padding: 10,
    marginVertical: 6,
    borderRadius: 10,
  },
  rowText: { color: '#1f2937', fontSize: 16 },
  small: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 6,
    borderRadius: 8,
  },
  smallText: { color: '#1f2937', fontSize: 14 },
  error: { color: '#ff6b6b', textAlign: 'center', marginTop: 10 },
  back: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    padding: 8,
    alignSelf: 'flex-start',
    marginTop: 20,
    borderRadius: 8,
  },
});
